sudo: required
services:
  - docker
language: go
go:
- '1.13'
jobs:
  include:
  - stage: "lint, unit test"
    before_script:
    - GOLANGCILINT_VERSION=1.21.0
    - GO111MODULE=on go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@v${GOLANGCILINT_VERSION}
    script:
    - make all
